apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cz0wubss8-go
  janus-idp.io/tekton: cz0wubss8-go
  backstage.io/kubernetes-id: cz0wubss8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cz0wubss8-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
