apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cz0wubss8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cz0wubss8-go 
  name: cz0wubss8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cz0wubss8-go 
